### ISSUE TITLE
Build and publish Debug packages on Windows

### ISSUE THREAD

**Issue by macumber** [NREL/conan-openstudio-ruby#10]

**Comment by jmarrec** [comment]
First step of this issue will be to determine whether that's going to quickly be hitting the bintray / travis / appveyor limits of some kind (build minutes, GB size, etc)

**Comment by macumber** [comment]
The other part of this task is to figure out why the debug builds are failing, I assume ci would hit the same issue as I am locally but it might not. we can make a separate ticket for that if needed.

**Comment by macumber** [comment]
We can live with just the debug build

**Comment by jmarrec** [comment]
I have both Release and Debug on my win10, they built fine.
