### ISSUE TITLE
Add CI 

### ISSUE THREAD

**Issue by macumber** [NREL/conan-openstudio-ruby#2]
Add CI which builds and pushes builds of OpenStudio's Ruby to bintray for conan https://github.com/NREL/conan-openstudio-ruby

**Comment by macumber** [comment]
Need to append the git sha to the builds so we always get the right package

**Comment by tijcolem** [comment]
This is done using Travis and Appveyor. See PR: https://github.com/NREL/conan-openstudio-ruby/pull/6

**Comment by macumber** [comment]
@tijcolem should we close the issue then?

**Comment by macumber** [comment]
Put in tagged `stable` and `latest` versions

**Comment by jmarrec** [comment]
@tijcolem I don't think Travis/Appveyor are configured correctly, or we need to document that better.

The latest builds are posting to `openstudio_ruby/2.5.5@commercialbuilding/stable` and not `openstudio_ruby/2.5.5@nrel/stable` like I would expect (cf: https://bintray.com/beta/#/commercialbuilding/nrel/). As a result openstudio's develop3 won't build right now.

If we want it to post to **nrel** and not **commercialbuilding** you need to do this:

```
CONAN_LOGIN_USERNAME=commercialbuilding
CONAN_USERNAME=nrel
```

**Comment by tijcolem** [comment]
Ah, okay I see this option in conan. I added the CONAN_LOGIN_USERNAME and CONAN_USERNAME changed and re-ran travis and the latest stable was posted to openstudio_ruby/2.5.5@nrel/stable so we should be good now.

**Comment by jmarrec** [comment]
Bintray is up to date with a stable and a testing channel
