### ISSUE TITLE
Patch source win32/Makefile.sub to use MSC_VER range instead of hardcoded one

### ISSUE THREAD

**Issue by jmarrec** [NREL/conan-openstudio-ruby#26]
`win32/Makefile.sub#538`

```
#if _MSC_VER != $(MSC_VER)
#error MSC version unmatch: _MSC_VER: $(MSC_VER) is expected.
#endif
```

MSVC 2019 has the range from 1920 to 1925 (currently), our current appveyor-built binary was on 1924, so if you use the latest MSVC 2019, you hit a hard error.

| Abbreviation  | Product name [Visual Studio version] †1 | VC ++ version †2 | _MSC_VER | _MSC_FULL_VER |
|---------------|-----------------------------------------|------------------|----------|---------------|
| 2019 Update 5 | Visual Studio 2019 version 16.5.1       | 14.25            | 1925     | 192528611     |
| 2019 Update 4 | Visual Studio 2019 version 16.4.0       | 14.24            | 1924     | 192428314     |
| 2019 Update 3 | Visual Studio 2019 version 16.3.2       | 14.21            | 1923     | 192328105     |
| 2019 Update 2 | Visual Studio 2019 version 16.2.3       | 14.21            | 1922     | 192227905     |
| 2019 Update 1 | Visual Studio 2019 version 16.1.2       | 14.21            | 1921     | 192127702     |
| 2019          | Visual Studio 2019 version 16.0.0       | 14.20            | 1920     | 192027508     |
| 2017 Update 9 | Visual Studio 2017 version 15.9.11      | 14.16            | 1916     | 191627030     |

**Comment by macumber** [comment]
@jmarrec +1, I just got hit by this after updating to Visual Studio 2019 version 16.5.1

**Comment by jmarrec** [comment]
I submitted a patch to ruby upstream, which apparently made it in (hard to tell with their issue tracker IMHO), but it isn't going to be backported. https://bugs.ruby-lang.org/issues/16763 

Patch was modified: https://bugs.ruby-lang.org/projects/ruby-master/repository/git/revisions/93edbb4c08856d6d10d0e2676cc2e36eef839a7d/diff

**Comment by jmarrec** [comment]
ruby github mirror: https://github.com/ruby/ruby/commit/93edbb4c08856d6d10d0e2676cc2e36eef839a7d
